name = input('What is your name?\n')
print('Hi, %s.' % name)
print("Welcome To Quiz Whiz!!")
name = input('Question one,What is The best movie in your opinion?\n')
print("Good Job!There Was No Answer!That was only up to you\n")
name = input("What is 10 times 10\n")
print("The Answer Was 100!")
name = input("Next Question, What is the captial of texas?\n")
print("The Answer Was Austin!")
name = input("Thanks For Playing! I Will Be Updating And Adding More Questions Soon!!!")
